# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0054_auto_20201005_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedMetadataRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_format', models.TextField(choices=[('sharev2_elastic', 'sharev2_elastic')])),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('formatted_metadata', models.TextField()),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.SourceUniqueIdentifier')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cachedelasticdoc',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cachedelasticdoc',
            name='suid',
        ),
        migrations.DeleteModel(
            name='CachedElasticDoc',
        ),
        migrations.AlterUniqueTogether(
            name='formattedmetadatarecord',
            unique_together=set([('suid', 'record_format')]),
        ),
    ]
